### ISSUE TITLE
./configure: line 4107: syntax error: unexpected

### ISSUE THREAD

**Issue by ChrisB9** [tideways/php-xhprof-extension#100]
Hi there,

I am currently building the xhprof-extension in a php8 environment
Since the newest php release php 8.0.0beta1 the configure execution renders the following error:

`./configure: line 4107: syntax error: unexpected "(" (expecting "fi")`

![image](https://user-images.githubusercontent.com/7099583/89637721-ee2a2200-d8aa-11ea-8ec5-37a98d19bb42.png)
`$as_echo_n "(cached) " >&6` -> this line is the culprit of that error.

I guess, something changed in the php-src developer-flags which in return triggers this.

The error is reproducable using this docker-setup:
https://github.com/ChrisB9/php8-xdebug

**Comment by beberlei** [comment]
Probably Alpines configure is a different version or something where the syntax is slightly different than on a common Linux ;-)

**Comment by ChrisB9** [comment]
That would mean, that the configuration should have never worked.
The last change in this repository happend in April and i am pulling from master.
Prior to Thursday, hence in the alpha3, it worked. I don't really think it is alpines fault here.

**Comment by khs1994** [comment]
@nikic

**Comment by nikic** [comment]
Should be fixed by https://github.com/php/php-src/commit/05478e985eb50c473054b4f1bf174f48ead78784.
