### ISSUE TITLE
No Sql message shown in the result

### ISSUE THREAD

**Issue by cash2910** [tideways/php-xhprof-extension#106]
phpVersion : 7.4
tidewaysVersion:   
   tideways_xhprof
   Version => 5.0.4
I Iog the result from the function  tideways_xhprof_disable() , Only find the trace of the request and some other information of the server .

**Comment by tourze** [comment]
same problem

**Comment by beberlei** [comment]
The SQL message is not part of the Callgraph in tideways_xhprof. You'll need to use our commerical product for that feature @ tideways.com
