### ISSUE TITLE
Ignoring call_user_func[_array]

### ISSUE THREAD

**Issue by krakjoe** [tideways/php-xhprof-extension#21]
PHP 7 broke this ability.

This morning I committed compiler option to allow it again.

```
ZEND_COMPILE_NO_BUILTINS
```

Will be available in 7.0.7+

Have a look at the [commit](http://git.php.net/?p=php-src.git;a=commit;h=9bbee305e3bb1d85ddad6bad92409818953207d5), it effects other functions, you may want to exclude them from profiles by default (is_string etc, meaningless to profile that stuff).

I intend to do a PR to fix it, but don't want to completely break CI, so will wait until tomorrow so nightly will pass at least :)

**Comment by beberlei** [comment]
@krakjoe How do you change the compiler_options in an extension? During MINIT? I suppose it can only affect the engine when you change this before a zend_compile is called, so this option affects how code is stored in opcache?

**Comment by krakjoe** [comment]
You only *have* to change them before compiler is invoked, many extensions do that ...

*Graceful* extensions should set them in RINIT, and restore them in RSHUTDOWN (xdebug does that, for example).

Opcache does not currently store the options code was compiled with, I have discussed this a little with dmitry, and he has suggested storing options in zend_script and zend_persistent_script. I'll poke him to do that ...

**Comment by beberlei** [comment]
@krakjoe I doubt this effort is worth it to make opcache aware of the options when caching, i was just wondering about how this affects opcache. But your statement about changing them before compiler is invoked is already everything I wanted to know. Will checkout what xdebug does to learn about this feature.

**Comment by beberlei** [comment]
Implemented in ac0062b
