### ISSUE TITLE
README example with outdated function names

### ISSUE THREAD

**Issue by spriebsch** [tideways/php-xhprof-extension#62]
README refers to tideways_xhprof_* functions, I guess it should be tideways_* instead.

**Comment by beberlei** [comment]
No, `tideways_xhprof_*` is correct. This extension `tideways_xhprof` was extracted out of our codebase that is now closed source and the open source part now handles only the XHProf part.

To get tideways our product and `tideways` extension it is available through the documentation and download section on our website.
