### ISSUE TITLE
rpm for version 4.1.6

### ISSUE THREAD

**Issue by hxpro** [tideways/php-xhprof-extension#69]
I use tideways-php at CentOS7 from yum repository defined like this:
```
[tideways]
baseurl = https://s3-eu-west-1.amazonaws.com/qafoo-profiler/rpm
enabled = 1
gpgcheck = 1
gpgkey = https://s3-eu-west-1.amazonaws.com/qafoo-profiler/packages/EEB5E8F4.gpg
name = Tideways

```
The new version `tideways-php-5.0.36` is not compatible with [xhgui](https://github.com/perftools/xhgui/). I don't know why, but the Error is `Call to undefined function tideways_enable()`. To quick fix I want to use older version 4.1.6, but I am not able to downgrade to this version from repository.
Please, how can I get tideways-php-4.1.6-1.x86_64.rpm? Yes, of course, I can build it myself...

**Comment by beberlei** [comment]
@hxpro the tideways-php package is soley for use with the "Tideways" service, not with xhgui. To get support for xgui you need to compile the master branch of this repository. We are not currently packaging the "tideways_xhprof" extension, it is something we plan to do in the future, but there is no ETA yet.
