### ISSUE TITLE
Any plans for PHP 7.3?

### ISSUE THREAD

**Issue by hotrush** [tideways/php-xhprof-extension#70]

**Comment by beberlei** [comment]
@hotrush The master branch compiles with PHP 7.3, what do you mean plans?

**Comment by hotrush** [comment]
@beberlei latest release doesn't work with 7.3. I don't know if code from master branch is stable and production ready

**Comment by beberlei** [comment]
@hotrush i pushed two new tags 4.1.7 and 5.0-beta3 which are both compatible with 7.3

**Comment by hotrush** [comment]
thanks

**Comment by hAtul89** [comment]
@beberlei  Hi. I'm not sure this is resolved or not, I have just created a post for XHGUI and not sure if the problem is actually with xhprof: 
Could you please review? 
https://github.com/perftools/xhgui/issues/260

**Comment by beberlei** [comment]
@hAtul89 you compiled tideways_xhprof against the wrong php. On multi php systems like Ubuntu/Debian this happens when you don't pass `--with-php-config` to `./configure` with the right path.
