### ISSUE TITLE
[Bug] Download DLL link broken

### ISSUE THREAD

**Issue by orklah** [tideways/php-xhprof-extension#71]
Hi,

When we follow the "Download DLL" on the README, we end up on this page:
https://ci.appveyor.com/project/tideways/php-profiler-extension

The download seem broken.

Thanks

**Comment by beberlei** [comment]
@orklah you need to click through to the build targeting your PHP version and architecture and then go to the "Artifacts" tab to see the ZIP download. Its not a link to the direct download.
