### ISSUE TITLE
Unable to build tideways.  Fatal error during make.

### ISSUE THREAD

**Issue by cyberpower678** [tideways/php-xhprof-extension#75]
When running the make command to build tideways, it always comes back with fatal error: 'php.h' file not found

Obviously there should be a php.h somewhere and it's not with the tideways.

**Comment by cyberpower678** [comment]
FTR, this was from following the instructions provided at https://tideways.com/profiler/xhprof-for-php7

**Comment by beberlei** [comment]
@cyberpower678 php.ini is part of the dev headers of php itself, what system are you on? on Ubuntu/Debian for example there is a `php7.2-dev` package that you need to install.

**Comment by cyberpower678** [comment]
I’m using macOS.

**Comment by cyberpower678** [comment]
Hello?   How do I install php-dev on MacOS?
