### ISSUE TITLE
Windows binaries for PHP 7.3 not built

### ISSUE THREAD

**Issue by Rarst** [tideways/php-xhprof-extension#78]
Hi! As far as I follow info PHP 7.3 is supported, but the suggested place to get Windows binaries doesn't seem to have 7.3 target at the moment https://ci.appveyor.com/project/tideways/php-profiler-extension

Can this be added please? Thanks in advance. :)

**Comment by beberlei** [comment]
Added the builds in https://github.com/tideways/php-xhprof-extension/commit/71be12cc56f64faefbbd4dbaa67d69955393adbd, they are still running for the first time right now but will be finished in an hour:
