### ISSUE TITLE
CPU time exceeds wall time on PHP 7.2 and is zero on PHP 7.3

### ISSUE THREAD

**Issue by vearutop** [tideways/php-xhprof-extension#81]
In case of nested function calls with both 4.1.7 and 5.0.0-beta3 and PHP 7.2.18 CPU time is zero or exceeds wall time ([v4](https://github.com/phperf/profiler-docker/blob/master/test/php_cpu_v4_72.json#L30), [v5](https://github.com/phperf/profiler-docker/blob/master/test/php_cpu_v5_72.json#L37)):
```
"nestedCPU==>nestedCPU@1": {
    "ct": 1,
    "wt": 5223,
    "cpu": 15625,
    "mu": 3208,
    "pmu": 0
}
```
```
"nestedCPU@1==>nestedCPU@2": {
    "ct": 1,
    "wt": 4052,
    "cpu": 0,
    "mu": 2624,
    "pmu": 0
},
```

In case of PHP 7.3.5 CPU time has zero value for all nodes ([v4](https://github.com/phperf/profiler-docker/blob/master/test/php_cpu_v4_73.json), [v5](https://github.com/phperf/profiler-docker/blob/master/test/php_cpu_v5_73.json)).

Reproducible with [`run_cpu.sh`](https://github.com/phperf/profiler-docker/blob/master/test/run_cpu.sh) and [`php_cpu.php`](https://github.com/phperf/profiler-docker/blob/master/test/php_cpu.php).

**Comment by beberlei** [comment]
I get these results for PHP 7.3.5, which are the expected https://gist.github.com/beberlei/240ad76e745db9a8b2786c91143c7d62 this is running on Ubuntu 18.10, No Docker.

Getting higher CPU than walltime must be caused by some kind of clock glitch. I am unsure about how Docker exposes these APIs to containers, I would need to investigate further.

**Comment by vearutop** [comment]
You're right, those results were taken with docker running in WSL, I now rechecked with docker on Mac and could not reproduce the issue with zero CPU time.

**Comment by beberlei** [comment]
@vearutop You were running the docker container under windows? Interesting, that probably has lots of implications on how the clock_gettime and rusage calls are emulated.

**Comment by vearutop** [comment]
@beberlei yes, under native Linux Docker in Windows' Windows Subsystem for Linux (not a Hyper-V Docker for Windows or VirtualBox Docker Machine). It works well most of the time I use it, so I totally forgot that the environment can be unstable at edge cases.
