### ISSUE TITLE
Execution time (wt) missing with 5.0.0, working perfectly 4.1.7 (MacOS)

### ISSUE THREAD

**Issue by stronk7** [tideways/php-xhprof-extension#87]
Not sure if this has been already commented, but have failed to find any reference.

Using locally compiled 5.0.0 all execution times are zero.  Previous, also locally compiled 4.1.7 returns wt properly.

macOS 10.14.6 18G103
Xcode 11.1 11A1027
PHP 7.3

Just detected when creating a Portfile for MacPorts: https://github.com/stronk7/macports-ports/blob/php-tideways_xhprof/php/php-tideways_xhprof/Portfile

(that one is working perfectly, but its 5.0.0 counterpart is not)

Ciao :-)

**Comment by beberlei** [comment]
Right, that was fixed in https://github.com/tideways/php-xhprof-extension/pull/86 - i didn't tag and release a v5.0.1 yet. Will do that asap.
