### ISSUE TITLE
Could you support for php-7.4?

### ISSUE THREAD

**Issue by nagaho** [tideways/php-xhprof-extension#90]

**Comment by beberlei** [comment]
@nagaho the master branch / v5.0 already compiles on PHP 7.4 release candidates. We are working on building it on our packaging stack so that it will get a release at latest once 7.4 is stable.

**Comment by nagaho** [comment]
Thank you. I'll check it.

**Comment by beberlei** [comment]
Packages here: https://github.com/tideways/php-xhprof-extension/releases/tag/v5.0.2
