### ISSUE TITLE
execution time

### ISSUE THREAD

**Issue by frequenc1** [tideways/php-xhprof-extension#95]
Is there an expected overhead for profiling per request? Historically I don't remember there being much of a slow down but in docker using nginx we are going from a couple hundred millisecs to 4-5 seconds turning on profiling.

**Comment by beberlei** [comment]
@frequenc1 That doesn't sound right. Can you check phpinfo() output of Tideways extension and tell me what the value for "Clock Source" is?

**Comment by frequenc1** [comment]
Yes! here is a bit of system info:

`phpinfo()
PHP Version => 7.3.16

System => Linux 7d577ac2c4e8 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64
...
tideways_xhprof

Version => 5.0.2
Clock Source => clock_gettime
`

`
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tideways_xhprof
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
`
This is run on OSX 10.14.6 using stretch docker container.

**Comment by beberlei** [comment]
@frequenc1 can you try setting `tideways_xhprof.clock_use_rdtsc=1` ini setting and try again?

**Comment by frequenc1** [comment]
Yes that is helping tremendously! Thank you. I did see this in the README.md but failed to noticed the name space change when I tried it.

> Tideways on Linux defaults to using clock_gettime(CLOCK_MONOTONIC), but if you are running on Xen based virtualization, you could try to reduce the overhead by setting `tideways.clock_use_rdtsc=1" in your PHP.ini.<

You might want to change that to `tideways_xhprof` instead of tideways. Is this standard for dockerized containers? I have an internal timer that gives load time of a page from laravel app middleware to terminal and those times are faster than the over all profile time. Should I assume that is from the overhead of xhprof and persisting the data?

**Comment by beberlei** [comment]
It might be a standard problem for Docker containers on *Mac*, but i don't know for sure. `clock_gettime` has usually a caching mechanism (VSDO) on Linux itself, it might be that this doesn't exist on Mac docker virtualization or works badly.

**Comment by beberlei** [comment]
Ref 9357da0
