### ISSUE TITLE
PHP 7.2 FPM installation

### ISSUE THREAD

**Issue by paul-gene** [tideways/php-xhprof-extension#98]
I successfully cloned the repo and ran the phpize and make commands.

I added the extension entry to my php7.2 fpm php.ini file and restarted php7.2-fpm and nginx, but phpinfo() does not show the extension as loaded.

**Comment by beberlei** [comment]
This sounds like the php extension is not correctly compiled against the right php version. Do you have multiple PHP versions installed on the machine?

**Comment by beberlei** [comment]
The important part then is to set the right phpize and php-config:

```
phpize7.2
./configure --with-php-config=/usr/bin/php7.2-config
make
```

**Comment by paul-gene** [comment]
That's exactly what happened!

I have multiple PHP versions installed, and I had ran `phpize` as the wrong version. Finally got it installed!
